const ERROR_CODE = {
	NORMAL: 0,
	DATABASE_INTERNAL_ERROR: 1,
	ACCOUNT_EXISTED_ERROR: 1001,
	ACCOUNT_NOT_EXIST_ERROR: 1002,
	ACCOUNT_PASSWORD_ERROR: 1003,
	ACCOUNT_ALREADY_LOGIN_ERROR: 1004,
}


module.exports = ERROR_CODE